services:
  domena-check:
    container_name: domena-check
    image: domena-check:0.1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"